version: '2'
services:
  orderly_server:
    image: docker.montagu.dide.ic.ac.uk:5000/orderly.server:${MONTAGU_ORDERLY_SERVER_VERSION}
    user: ${ORDERLY_SERVER_USER_ID}
    command: /orderly
    ports:
      - "8321:8321"
    volumes:
      - ${MONTAGU_ORDERLY_PATH}:/orderly
