steps:
  - label: ":mag: Run tests"
    commands:
      - scripts/clear-docker.sh
      - buildkite/pull_docker_images.sh
      - buildkite/migrate-build.sh
      - buildkite/run_dependencies.sh
      - scripts/clear-docker.sh
