steps:
    - label: "Make migrate image"
      commands: buildkite/make-migrate-image.sh

    - wait

    - label: "Build and test app"
      commands: buildkite/build-app.sh

    - label: "Run custom config tests in container"
        commands: buildkite/run-custom-config-tests-in-container.sh
