steps:
  - label: ":mag: Run tests"
    commands:
      - scripts/clear-docker.sh
      - buildkite/pull_docker_images.sh
      - buildkite/migrate_build.sh
      - buildkite/run_dependencies.sh
      - ./src/gradlew -p src :customConfigTests:copyDemo
      - ./src/gradlew -p src :app:test
      - ./src/gradlew -p src :customConfigTests:test --stacktrace
      - scripts/clear-docker.sh
