comments:
  active: false

complexity:
  active: false

formatting:
  Indentation:
    active: false
  NoLineBreakAfterElse:
    active: false
  NoWildcardImports:
    active: false
  SpacingAroundCurly:
    active: false
  SpacingAroundKeyword:
    active: false
  ParameterListWrapping:
    active: false

style:
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  WildcardImport:
    active: false
