version: '2'
services:
  proxy:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-reverse-proxy-minimal:master
    ports:
    - 80:80
    depends_on:
    - api
  orderly_server:
    image: docker.montagu.dide.ic.ac.uk:5000/orderly.server:${MONTAGU_ORDERLY_SERVER_VERSION}
    user: ${ORDERLY_SERVER_USER_ID}
    command: /orderly
    ports:
      - "8321:8321"
    volumes:
      - ${MONTAGU_ORDERLY_PATH}:/orderly
  api:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-api:master
    ports:
    - "8080:8080"
    depends_on:
    - db
  db:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-db:master
    ports:
    - "5432:5432"
